version: "3"
services:
  app:
   build: ./
   ports:
   - "8080:80"
   volumes:
   - "./app/:/opt/app/"
   - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
  backend:
   build: ./
   volumes:
   - "./nginx-back.conf:/usr/local/openresty/nginx/conf/nginx.conf"
